<?xml version="1.0"?>
<!-- 5 DOF Revolute Manipulator -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rarm" >

  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" />       <!-- arbitrary value for mass -->
  <xacro:property name="b_length" value="0.5" /> <!-- base length -->
  <xacro:property name="b_width" value="0.25" />  <!-- base width -->
  <xacro:property name="b_height" value="0.25" /> <!-- base height -->

  <xacro:property name="length" value="0.09" />   <!-- links length -->
  <xacro:property name="width" value="0.0436" />  <!-- links width -->
  <xacro:property name="height" value="0.025" />  <!-- links height -->
  <xacro:property name="radius" value="0.075" />  <!-- links radius -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find rarm_description)/urdf/rarm.gazebo" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <!-- Base Link -->
  <link name="base">
    <collision>
      <origin xyz="0 0 ${b_height/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${b_length} ${b_width} ${b_height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${b_height/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${b_length} ${b_width} ${b_height}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 ${b_height/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="fixed1" type="fixed">
    <parent link="world"/>
    <child link="base"/>
  </joint>

  <link name="link0">
    <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${radius}" length=".05"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<cylinder radius="${radius}" length="0.05"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="fixed2" type="fixed">
    <axis xyz="0 0 1"/>
    <parent link="base"/>
    <child link="link0"/>
    <origin xyz="${b_length/2 - radius} 0 ${b_height}" rpy="0 0 0"/>
    <!-- limit effort="100" velocity="100" / -->
    <!-- joint_properties damping="0.0" friction="0.0" / -->
  </joint>

  <link name="link1">
    <collision>
      <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
      <geometry>
	<box size="${length} ${width} ${height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
      <geometry>
	<box size="${length} ${width} ${height}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="joint1" type="revolute">
    <axis xyz="0 0 1"/>
    <parent link="link0"/>
    <child link="link1"/>
    <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
    <limit lower="${-pi*3/4}" upper="${pi*3/4}" effort="1000" velocity="10" />
    <joint_properties damping="0.0" friction="0.0" />
  </joint>

  <link name="link2">
    <collision>
      <origin xyz="${length/2} 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
	<box size="${length} ${width} ${height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${length/2} 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
	<box size="${length} ${width} ${height}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="${length/2} 0 0" rpy="${PI/2} 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="joint2" type="revolute">
    <axis xyz="0 0 1"/>
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 ${length - 0.05}" rpy="${-PI/2} ${-PI/2} 0"/>
    <limit lower="${-pi*3/4}" upper="${pi*3/4}" effort="1000" velocity="10" />
    <joint_properties damping="0.0" friction="0.0" />
  </joint>

  <link name="link3">
    <collision>
      <origin xyz="${length/2} 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
	<box size="${length} ${width} ${height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${length/2} 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
	<box size="${length} ${width} ${height}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="${length/2} 0 0" rpy="${PI/2} 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="joint3" type="revolute">
    <axis xyz="0 0 1"/>
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="${length} 0 0" rpy="0 0 0"/>
    <limit lower="${-pi*3/4}" upper="${pi*3/4}" effort="1000" velocity="10" />
    <joint_properties damping="0.0" friction="0.0" />
  </joint>

  <link name="link4">
    <collision>
      <origin xyz="${length/2} 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
	<box size="${length} ${width} ${height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${length/2} 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
	<!-- box size="${length} ${width} ${height}"/ -->
	<mesh filename="package://rarm_description/meshes/links.dae" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="${length/2} 0 0" rpy="${PI/2} 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="joint4" type="revolute">
    <axis xyz="0 0 1"/>
    <parent link="link3"/>
    <child link="link4"/>
    <origin xyz="${length} 0 0" rpy="0 0 0"/>
    <limit lower="${-pi*3/4}" upper="${pi*3/4}" effort="1000" velocity="10" />
    <joint_properties damping="0.0" friction="0.0" />
  </joint>

  <link name="link5">
    <collision>
      <origin xyz="${length/2} 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
	<box size="${length} ${width} ${height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${length/2 -0.005} 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
	<!-- box size="${length} ${width} ${height}"/ -->
        <mesh filename="package://rarm_description/meshes/links.dae" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="${length/2} 0 0" rpy="${PI/2} 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="joint5" type="revolute">
    <axis xyz="0 0 1"/>
    <parent link="link4"/>
    <child link="link5"/>
    <origin xyz="${length} 0 0" rpy="0 0 0"/>
    <limit lower="${-pi*3/4}" upper="${pi*3/4}" effort="1000" velocity="10" />
    <joint_properties damping="0.0" friction="0.0" />
  </joint>



  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint3">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran4">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint4">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor4">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran5">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint5">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor5">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


</robot>
